driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.1
  - name: fedora-21
  - name: fedora-22
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-15.04
    run_list:
    - recipe[apt]
  - name: debian-6.0.10
  - name: debian-7.8
  - name: debian-8.0

suites:
  #
  # server22-single
  #
  - name: server22-single
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'debian-6.0.10',
      'debian-7.8',
      'centos-5.11',
      'centos-6.6',
      'ubuntu-12.04',
    ]
    attributes:
      httpd:
        version: '2.2'

  #
  # server24-default
  #
  - name: server24-single
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'debian-8.0',
      'fedora-21',
      'fedora-22',
      'ubuntu-14.04',
      'ubuntu-15.04',
      'centos-7.1',
    ]
    attributes:
      httpd:
        version: '2.4'
        listen_addresses: [
          '0.0.0.0'
        ]
